version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: Portofolio
    ports:
      - "5173:5173"
    volumes:
      - .:/app        
      - /app/node_modules  
    command: npm run dev -- --host
    environment:
      - CHOKIDAR_USEPOLLING=true